# Generated by Django 4.2.6 on 2023-12-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_answer_created_question_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='ronaldo.jpg', null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
