# Generated by Django 4.2.6 on 2023-12-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='author',
        ),
    ]
