# Generated by Django 4.2.6 on 2023-12-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_user_answer_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='author',
            new_name='user',
        ),
    ]
